#pragma once


namespace zebra::ast::symbol {

	enum ZLangConstruct {
		Z_PROGRAM,
		Z_COMPILATION_UNIT,
		Z_TYPE_PARAM,
		Z_VARIANT_TYPE_PARAM,
		Z_TYPE_PARAM_ARGS,
		Z_TRAIT_DEF,
		Z_IMPORT,
		Z_BLOCK,
		Z_F_WRAPPER,
		Z_STMT_LIST,
		Z_PARAM_DEFAULT_EXPR,
		Z_CLASS_PARAM_DEFAULT_EXPR,
		Z_CLASS_DEF, Z_OBJECT_DEF, Z_ACCESS_MODIFIER,
		Z_TYPE, Z_TYPE_LIST, Z_PARAM_TYPE, Z_VALUE_DCL,
		Z_TYPE_PARAMS, Z_VARIANT_TYPE_PARAMS,
		 Z_REG_FUNC_DEF, Z_THIS_FUNC_DEF,Z_IMPORT_LIST, Z_FUN_SIG, Z_PARAM_LIST, Z_SELF_TYPE,
		Z_PROD_SUB_TREE_NOD,
		Z_IF, Z_WHILE,  Z_MODIFIERS, Z_CASE_CLAUSE, Z_CASE_CLAUSES, Z_CLASS_CONSTR, Z_CLASS_PARAM, Z_CLASS_PARAMS,
		Z_CLASS_PARAM_CLAUSES, Z_CLASS_PARENTS, Z_CLASS_TEMPLATE, Z_CONSTR_BLOCK, Z_FOR,
		 Z_GENERATOR,  Z_PARAM, Z_PARAM_CLAUSES,
		Z_PARAM_TYPES, Z_RETURN, Z_TEMPLATE,  Z_TEMPLATE_BODY, Z_THIS_FUN,
		 Z_TRY,	 Z_TYPE_DEF,  Z_TYPE_PARAM_CLAUSE,



	};
}