#pragma once

#include "ast/leaf/fVariantTypeParam.hpp"
#include "ast/leaf/fType.hpp"

namespace zebra::ast::symbol {

	enum ZLangConstruct {
		Z_PROGRAM,
		Z_COMPILATION_UNIT,
		Z_TYPE_PARAM,
		Z_VARIANT_TYPE_PARAM,
		Z_TRAIT,
		Z_IMPORT,
		Z_PARAM_DEFAULT_EXPR,
		Z_CLASS_PARAM_DEFAULT_EXPR,
		Z_CLASS_DEF,
		Z_TYPE, Z_PARAM_TYPE,
		Z_DECL, Z_REG_FUNC, Z_THIS_FUNC,
		Z_PROD_SUB_TREE_NOD,
		Z_IF, Z_WHILE,  Z_CASE_CLAUSE, Z_CASE_CLAUSES, Z_CLASS_CONSTR, Z_CLASS_PARAM,
		Z_CLASS_PARAM_CLAUSES, Z_CLASS_PARENTS, Z_CLASS_TEMPLATE, Z_CONSTR_BLOCK, Z_FOR,
		Z_FFUN,  Z_FUN_SIG,  Z_GENERATOR, Z_NAMED_FUN, Z_OBJECT, Z_PARAM, Z_PARAM_CLAUSES,
		Z_PARAM_TYPES, Z_RETURN, Z_TEMPLATE,  Z_TEMPLATE_BODY, Z_THIS_FUN,
		Z_TRAIT_DEF, Z_TRY,	Z_TYPE_ARGS, Z_TYPE_DEF, Z_VALUE_DECL, Z_TYPE_PARAM_CLAUSE,



		Z_VALUE_DEF


	};
}